### ISSUE TITLE
The new asyncio `server_forever()` implementation in 17.0 has broken compatibility with `uvloop`

### ISSUE THREAD

**Issue by pmarcelll** [python-websockets/websockets#1746]
The improved `serve_forever()` introduced in https://github.com/python-websockets/websockets/pull/1745 relies on CPython's private _serving_forever_fut attribute, which breaks compatibility with `uvloop`, since it utilizes its own Cython-based `Server` implementation:

```
  File "/home/dockeruser/.local/lib/python3.12/site-packages/websockets/asyncio/server.py", line 534, in serve_forever
    if self.server._serving_forever_fut is not None:  # type: ignore[attr-defined]
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'uvloop.loop.Server' object has no attribute '_serving_forever_fut'
```

**Comment by aaugustin** [comment]
Ah, I didn't see that one coming... I'll fix it.

**Comment by aaugustin** [comment]
Fixed in eb3600ce789ca8e19ecda5f07bad68b66fe1a762. I will release 17.0.1 with this fix ~now~ as soon as I fix another bug which I just discovered.

**Comment by aaugustin** [comment]
Thank you for letting me know!

**Comment by aaugustin** [comment]
17.0.1 is on PyPI now.
