### ISSUE TITLE
speedups.c is missing from the 13.0 source distribution

### ISSUE THREAD

**Issue by BwL1289** [python-websockets/websockets#1494]
`speedups.c` is missing from source distribution. This is a regression of #1329.

To reproduce:
1. Download source dist from https://files.pythonhosted.org/packages/0f/b0/e53bdd53d86447d211694f3cf66f163d077c5d68e6bcaa726bf64e88ae3a/websockets-13.0.tar.gz
2. `tar ztvf /Downloads/websockets-13.0.tar.gz | grep speedups` 
```
-rw-r--r--  0 runner docker     55 Aug 20 08:23 websockets-13.0/src/websockets/speedups.pyi
```

compilation error:
```
/opt/llvm_toolchain/bin/clang -std=gnu17 <redacted> -I/usr/local/include -fPIC -I/usr/local/include/python3.12 -c src/websockets/speedups.c -o build/temp.linux-aarch64-cpython-312/src/websockets/speedups.o
  clang: error: no such file or directory: 'src/websockets/speedups.c'
  error: command '/opt/llvm_toolchain/bin/clang' failed with exit code 1
```

**Comment by aaugustin** [comment]
Oops. Probably a regression from 4d0e0e10c6ebb779780a9e590667661381df78dc. I'll fix it.

**Comment by BwL1289** [comment]
@aaugustin thank you!

**Comment by aaugustin** [comment]
New release (13.0.1) is on PyPI.

I checked that https://files.pythonhosted.org/packages/8f/1c/78687e0267b09412409ac134f10fd14d14ac6475da892a8b09a02d0f6ae2/websockets-13.0.1.tar.gz has speedups.c.
