### ISSUE TITLE
object has no attribute 'fail_connection' after upgrading to 14.0

### ISSUE THREAD

**Issue by carlosmiei** [python-websockets/websockets#1547]
After upgrading Websockets to 14.0 we now get `object has no attribute 'fail_connection'` so I'm assuming this method was removed.

Is there an alternative method for it?

Thank you for your work on this amazing project!

**Comment by aaugustin** [comment]
Check the "backwards-incompatible changes" section of the changelog to buy five years by sticking to the legacy implementation.

This was never a public API so you're on your own to upgrade to the new asyncio implementation. You may try this:

```python
            async with ws.send_context():
                ws.protocol.fail(code, reason)
```

But I'm not sure it buys you anything meaningful over `ws.close(code, reason)`?

**Comment by carlosmiei** [comment]
@aaugustin 

I was not the one adding `fail_connection` initially but now I'm maintaining that code.

Nonetheless I will replace it with `close`.

Thank you.

**Comment by aaugustin** [comment]
If you don't have any information about why it's that way and `close()` seems to work, yeah, sounds reasonable!
